#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Productivity_Tracker.Resource", IsApplication=true)]

namespace Productivity_Tracker
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050000
			public const int theme_custom_background = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int theme_devicedefault_background = 2131034113;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int icon_notification = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070015
			public const int b_Clear = 2131165205;
			
			// aapt resource value: 0x7f070013
			public const int b_TimeMax = 2131165203;
			
			// aapt resource value: 0x7f070011
			public const int b_TimeMin = 2131165201;
			
			// aapt resource value: 0x7f070001
			public const int buttonAwesome = 2131165185;
			
			// aapt resource value: 0x7f07001a
			public const int buttonBackSummary = 2131165210;
			
			// aapt resource value: 0x7f07000c
			public const int buttonClear = 2131165196;
			
			// aapt resource value: 0x7f070002
			public const int buttonGood = 2131165186;
			
			// aapt resource value: 0x7f070009
			public const int buttonMain = 2131165193;
			
			// aapt resource value: 0x7f070003
			public const int buttonMediocre = 2131165187;
			
			// aapt resource value: 0x7f07000a
			public const int buttonOptions = 2131165194;
			
			// aapt resource value: 0x7f070004
			public const int buttonPoor = 2131165188;
			
			// aapt resource value: 0x7f07000d
			public const int buttonRawData = 2131165197;
			
			// aapt resource value: 0x7f070008
			public const int buttonSummary = 2131165192;
			
			// aapt resource value: 0x7f070005
			public const int buttonTerrible = 2131165189;
			
			// aapt resource value: 0x7f070007
			public const int linearLayout1 = 2131165191;
			
			// aapt resource value: 0x7f07000f
			public const int linearLayout2 = 2131165199;
			
			// aapt resource value: 0x7f070006
			public const int relativeLayout1 = 2131165190;
			
			// aapt resource value: 0x7f070014
			public const int t_ClearData = 2131165204;
			
			// aapt resource value: 0x7f070012
			public const int t_TimeMax = 2131165202;
			
			// aapt resource value: 0x7f070010
			public const int t_TimeMin = 2131165200;
			
			// aapt resource value: 0x7f07000b
			public const int textFeeling = 2131165195;
			
			// aapt resource value: 0x7f070019
			public const int textSummary = 2131165209;
			
			// aapt resource value: 0x7f070018
			public const int textSummaryLeast = 2131165208;
			
			// aapt resource value: 0x7f070016
			public const int textSummaryMost = 2131165206;
			
			// aapt resource value: 0x7f070000
			public const int titleFeeling = 2131165184;
			
			// aapt resource value: 0x7f070017
			public const int titleSummaryLeast = 2131165207;
			
			// aapt resource value: 0x7f07000e
			public const int titleSummaryMost = 2131165198;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int MainOri = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Options = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Summary = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int SummaryOri = 2130903044;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int Theme_Custom = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
